// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2WyyvkAn4ZEmelYQnEZ77_jfZqLNXoM',
    appId: '1:13203529616:web:e70b97e93dd0662580dd15',
    messagingSenderId: '13203529616',
    projectId: 'threads-clone-a7753',
    authDomain: 'threads-clone-a7753.firebaseapp.com',
    storageBucket: 'threads-clone-a7753.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKUN3RiGhms5TnyxosKb_HaXu67AdIz3E',
    appId: '1:13203529616:android:e44655b574fc3c3b80dd15',
    messagingSenderId: '13203529616',
    projectId: 'threads-clone-a7753',
    storageBucket: 'threads-clone-a7753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yYD8RvSO5jCZ7BBJI7Y3snHBOiAEK8g',
    appId: '1:13203529616:ios:c06bdf280f550d0980dd15',
    messagingSenderId: '13203529616',
    projectId: 'threads-clone-a7753',
    storageBucket: 'threads-clone-a7753.firebasestorage.app',
    iosBundleId: 'com.example.flutterThreadsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2yYD8RvSO5jCZ7BBJI7Y3snHBOiAEK8g',
    appId: '1:13203529616:ios:c06bdf280f550d0980dd15',
    messagingSenderId: '13203529616',
    projectId: 'threads-clone-a7753',
    storageBucket: 'threads-clone-a7753.firebasestorage.app',
    iosBundleId: 'com.example.flutterThreadsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2WyyvkAn4ZEmelYQnEZ77_jfZqLNXoM',
    appId: '1:13203529616:web:0c3e2c021a3c683f80dd15',
    messagingSenderId: '13203529616',
    projectId: 'threads-clone-a7753',
    authDomain: 'threads-clone-a7753.firebaseapp.com',
    storageBucket: 'threads-clone-a7753.firebasestorage.app',
  );

}